name: Feature Request
description: Suggest a feature request to help us improve the over-all playing experience.
title: "[Feature]: "
labels: ["feature"]
assignees:
  - toxocious
body:
  - type: markdown
    attributes:
      value: |
        We appreciate you taking the time to fill out a feature request, and are looking forward to hearing about what you'd like to see implemented.
  - type: textarea
    id: describe-the-feature
    attributes:
      label: Describe The Feature
      description: Give us a clear and concise description of what the feature is.
      placeholder: I would like to see something that..
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe how you would go about implementing this feature.
      placeholder: To implement this feature, I would..
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Is there anything else you want to say about this feature?
    validations:
      required: false
  - type: textarea
    id: anything-else
    attributes:
      label: Anything Else
      description: |
        Links? Pictures? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
